### ISSUE TITLE
soulsiphon items do not show up in creative inventory 

### ISSUE THREAD

**Issue by crazysmile11012** [Negative-light/soulsiphon#10]
![2023-05-30_20 44 38](https://github.com/Negative-light/soulsiphon/assets/107813207/91fd5303-3f66-4bba-ae21-a3a2db080103)
![2023-05-30_20 45 00](https://github.com/Negative-light/soulsiphon/assets/107813207/bcdc9d16-23e4-4ac9-82f5-dea9ffe1f0df)

**Comment by crazysmile11012** [comment]
you can get them via commands tho

**Comment by Negative-light** [comment]
This is a Known Bug will be fixed in next Release
