### ISSUE TITLE
automatable with hoppers 

### ISSUE THREAD

**Issue by crazysmile11012** [Negative-light/soulsiphon#13]
be able to put hopper in from the side and out comes soul item/filled earn

**Comment by Negative-light** [comment]
This would be consistent with how the Nether Anchor works.
@Healex2 thoughts

**Comment by crazysmile11012** [comment]
dead chat xd

**Comment by Negative-light** [comment]
Not sure of we are doing this in the base mod

**Comment by crazysmile11012** [comment]
@Healex2  just axed it , such a bummer
