### ISSUE TITLE
bigger urns

### ISSUE THREAD

**Issue by crazysmile11012** [Negative-light/soulsiphon#16]
there could be a urn with a larger capacity that get filled up further each time u right click of a filled cauldron with a cap of 4 this could yield farther storage capacity (at the expense of resources to craft progresfuly more large urns)

**Comment by Healex2** [comment]
Nothing currently uses multiple souls, so I see no reason to implement urns of various sizes. If we ever make them into decorative blocks, I will reconsider then.
