### ISSUE TITLE
Weeping Urn Crafting

### ISSUE THREAD

**Issue by Healex2** [Negative-light/soulsiphon#2]
craftRemainder @ Weeping Urn (WU): Empty Weeping Urn (EWU) 
All recipes below are shapeless: 
 :: Sand + WU -> Soul Sand 
 :: Red Sand + WU -> Soul Soil 
 :: Torch + WU -> Soul Torch 
 :: Lantern + WU -> Soul Lantern 
 :: Campfire + WU -> Soul Campfire 
 
 Please note that the following recipe is not intended to be in the mod: 
  :: Glass Bottle + WU -> Bottle O' Enchanting

**Comment by Negative-light** [comment]
Weeping Urn Craft was completed on first Release
