### ISSUE TITLE
Soul Dipping (Use item on Filled Sculk Cauldron)

### ISSUE THREAD

**Issue by Healex2** [Negative-light/soulsiphon#3]
When using the items below on a filled Sculk Cauldron, they result in the items also shown below.
 :: Empty Weeping Urn -> Weeping Urn 
 :: Sand -> Soul Sand 
 :: Red Sand  -> Soul Soil 
 :: Glass Bottle  -> Bottle O' Enchanting 
 :: Torch -> Soul Torch 
 :: Lantern -> Soul Lantern 
 :: Campfire -> Soul Campfire

**Comment by Negative-light** [comment]
Soul Drip was added in the first realease
