### ISSUE TITLE
Soul Siphoning

### ISSUE THREAD

**Issue by Healex2** [Negative-light/soulsiphon#4]
Similar to how when mud placed over dripstone the mud is turned into clay.
Instead of Mud: Soul Sand or Soul Soil
Instead of Dripstone: Soul Siphon (still facing down as a stalactite like the dripstone)
Instead of Clay: Sand (resulting from Soul Sand) or Red Sand (resulting from Soul Soil)

**Comment by Negative-light** [comment]
This was a baisc feature added early on
